"""instial migration

Revision ID: 0d7b6f0f8de9
Revises: e128c9cec84f
Create Date: 2016-05-24 20:11:47.503446

"""

# revision identifiers, used by Alembic.
revision = '0d7b6f0f8de9'
down_revision = 'e128c9cec84f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
